site_name: Django + HTMX tutorial
site_url:
site_description: A tutorial for building the RealWorld app in Django and HTMX
repo_url: https://github.com/harabat/django-htmx
repo_name: harabat/django-htmx
docs_dir: 'tutorial/docs'
site_dir: 'tutorial/site'

theme:
  name: material
  logo: assets/django-logo.png
  favicon: assets/django-logo.png
  icon:
    repo: octicons/mark-github-16
  language: en
  custom_dir: 'tutorial/overrides'
  # include_homepage_in_sidebar: true  # no effect
  # sticky_navigation: true  # no effect
  # collapse_navigation: true  # no effect
  features:
    - navigation.instant
    - navigation.expand
    - navigation.top
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search:
      prebuild_index: true
      separator: '[\s\-\.]'
  # - social  # generate social cards

extra:
  social:
    - icon: octicons/mark-github-16
      link: https://github.com/harabat/django-htmx
      name: Django + HTMX tutorial on GitHub

markdown_extensions:
  # https://facelessuser.github.io/pymdown-extensions/extensions/
  # - attr_list  # for align
  # - md_in_html  # better done by pandoc
  # - footnotes
  - admonition  # callouts
  - tables  # tables
  - pymdownx.details  # information in dropdowns
  - toc:
      permalink: "#"  # anchors for headings
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.tabbed  # for tabs
  - pymdownx.tasklist:
      custom_checkbox: true  # for lists with checkboxes

nav:
  - Readme: index.md
  - Starting the project: 01_starting_the_project.md
  - First views and templates: 02_first_views_and_templates.md
  - Viewing Articles: 03_viewing_articles.md
  - Creating, editing, and deleting Articles: 04_creating_editing_and_deleting_articles.md
  - Comments: 05_comments.md
  - Users and Profiles: 06_users_and_profiles.md
  - Authentication: 07_authentication.md
  - Securing the app: 08_securing_the_app.md
  - Profile features: 09_profile_features.md
  - Editing profiles: 10_editing_profiles.md
  - Follows: 11_follows.md
  - Favourites: 12_favourites.md
  - Tags: 13_tags_coming_soon.md
  - HTMX: 14_htmx_coming_soon.md
  - Future extensions: 15_future_extensions.md
