# Generated by Django 3.2.9 on 2021-12-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='Description', max_length=2000),
        ),
    ]
