# Generated by Django 3.2.9 on 2021-12-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default='Description', max_length=2000),
        ),
    ]
